2/15/2019: Pi restarted before trip, did not use remote view since then 
3/1/2019: Crashed (flask) checking 3/1/2019, restarted Pi
(Note garage heater problems Thu Feb 28 so high was then around 45
fixed Tue March 5)
3/12/2019 Crashed after using remote access. Restarted 3/13/19 10:50 am
3/21/2019 Restarted before Spain trip
4/3/2019 9 pm  Crash, mouse or keyboard not recognized
4/17/2019 Crashed 11 am (monitor stopped first)
(note 4/20, 4/23, 4/24 restarted just admonitor.py)
4/27/2019 Crashed 3 am, 8 am no screen had to power up again
5/16/2019 1:50 pm seemed to stop getting readings- Restarted
5/30/2019 adsmonitor.py developed to use signaling to avoid
hanging on opening connections to probes
6/11/2019 Pi crashed - myflaskd pipe problem and pi froze - restarted
(note adsmonitor.py seemed to still be running)
6/19/2019 Restarted - Replaced outdoor DH11
6/24/2019 Restarted pre DC trip (Note, when just closed os window and 
tried to restart myflaskd.py, it didn't work. So, restarted.

Could not read 141.133.76.227 try 5 at 2020-01-07 16:45:33
*** read error at *** 2020-01-07 16:45:35.123635
No temperature available, skipped ***** ID =43  T =2020-01-07 16:45:15.095452
Signal handler called with signal 14
Traceback (most recent call last):
  File "adsmonitor.py", line 418, in <module>
    time.sleep(nextSleepSec)
  File "adsmonitor.py", line 118, in handler
    raise IOError("Couldn't open device!")
IOError: Couldn't open device!

+


Could not read 141.133.76.227 try 5 at 2019-11-26 11:44:02
*** read error at *** 2019-11-26 11:44:04.029184
No temperature available, skipped ***** ID =43  T =2019-11-26 11:40:15.003923
Signal handler called with signal 14
Traceback (most recent call last):
  File "adsmonitor.py", line 418, in <module>
    time.sleep(nextSleepSec)
  File "adsmonitor.py", line 118, in handler
    raise IOError("Couldn't open device!")
IOError: Couldn't open device!
